### ISSUE TITLE
Add test coverage report integration

### ISSUE THREAD

**Issue by manorie** [GosSearch/gosse-core#11]
Maybe coveralls?

**Comment by hevalberknevruz** [comment]
Coveralls is very well but I looked, doesn't have integration snap-ci.

**Comment by hevalberknevruz** [comment]
No problem for me, I can change that If you want to change to continuous integration

**Comment by manorie** [comment]
It does not matter for me also, but it can be good to add coverage report. What ever you like if you can add, add it bro.

**Comment by hevalberknevruz** [comment]
I will research. I will change it that  If doesn't have another way.
