### ISSUE TITLE
Adding Travis CI or something similar to project.

### ISSUE THREAD

**Issue by manorie** [GosSearch/gosse-core#5]
Projeye Travis CI gibi bir test otomasyonu ekleyelim derim, issue yu actim ustlenen eklesin.
Olmadi ben yapmistim bikere bir projeme ondan copy paste eklerim. Ustune almak isteyen olursa assign etsin kenini.

**Comment by hevalberknevruz** [comment]
Travis güzel tercih ama ThoughtWorks'un Snap-CI da bakabiliriz. Bizim ihtiyacımızı karşılayacak ayarda ücretsiz zaten. @manorie  Bunu ilerisi için deneyim olabilir diye söylüyorum aksi takdir de çok da önemli bir detay değil yani Travis de güzel ürün.

**Comment by hevalberknevruz** [comment]
Static Code Analyze toolları varya onuda pipeline dahil edelim belli bir technical debt üzerindeyse geçmesin. O değere yaklaştıkça da kodumuzu temizleriz. Coverage arttırırız vs. vs.

**Comment by manorie** [comment]
Bu acil degil diye Asisign etmedim kendimi, ilgilenen olursa alsin ustune bir iki test yazilinca, thoughtworksun tooluda olabilir bana fark etmez CI olsun yeter

**Comment by hevalberknevruz** [comment]
Tamam bir draft çıksın ben hallederim o işi.
